version: "3.9"
services:
  fisioterapia-db:
    image: mysql:8.0
    container_name: fisioterapia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # contraseña del usuario root
      MYSQL_DATABASE: fisioterapia-backend      # nombre de la base de datos
      MYSQL_USER: luffy         # usuario adicional
      MYSQL_PASSWORD: luffy     # contraseña del usuario adicional
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
